name: watch_fhir
description: Lightweight FHIR Server to act as Central Hub for Listening, Updating, Transforming or to act as a Proxy Server.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  at_client: ^3.0.64
  at_onboarding_cli: ^1.3.0
  fhir: ^0.11.3
  googleapis: ^10.1.0
  http: ^1.1.0
  googleapis_auth: ^1.4.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  version: ^3.0.2

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.1
  test: ^1.24.6

dependency_overrides:
  http: ^1.0.0
