name: watch_fhir
description: Lightweight FHIR Server to act as Central Hub for Listening, Updating, Transforming or to act as a Proxy Server.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  at_client: ^3.0.67
  at_onboarding_cli: ^1.3.0
  fhir: ^0.11.4
  fhir_at_rest: ^0.11.4
  fhir_path: ^0.11.2
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  version: ^3.0.2
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  # flutter pub run import_sorter:main
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  lints: ^3.0.0
  mockito: ^5.4.2
  riverpod_generator: ^2.3.5
  test: ^1.24.9

dependency_overrides:
  uuid: ^4.1.0
  http: ^1.1.0
