name: watch_fhir
description: Lightweight FHIR Server to act as Central Hub for Listening, Updating, Transforming or to act as a Proxy Server.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  at_client: ^3.0.64
  at_onboarding_cli: ^1.3.0
  fhir: ^0.11.3
  fhir_path: ^0.11.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  googleapis: ^10.1.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  version: ^3.0.2
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  # flutter pub run import_sorter:main
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  lints: ^2.1.1
  test: ^1.24.6

dependency_overrides:
  http: ^1.0.0
